apiVersion: v1
kind: Pod
metadata:
  name: mongo-db
  labels:
    app: mongo
spec:
  containers:
  - name: mongo-container
    image: mongo:latest
    ports:
    - containerPort: 27017
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      valueFrom:
        secretKeyRef:
          name: mongodb-secret # name of the k8s secret created by external-secrets
          key: user # key in the k8s secret
    - name: MONGO_INITDB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mongodb-secret
          key: password
    - name: MONGO_INITDB_DATABASE
      valueFrom:
        secretKeyRef:
          name: mongodb-secret
          key: database
    volumeMounts:
    - name: mongo-data
      mountPath: /bitnami/mongo
  volumes:
  - name: mongo-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-database
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
---