apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secretstore-aws
spec:
  refreshInterval: 600 # refresh interval to sync secrets & use pull based method
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1 
      auth:
        secretRef: # local k8s authentication to aws secrets manager ( use only for local dev & there is no IRSA )
          accessKeyIDSecretRef:
            name: aws-creds # reference to secret containing aws creds & must create this secret first
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-creds # reference to secret containing aws creds & must create this secret first
            key: secret-access-key
